[engine]
name = "wasm-register-bank-example"
max_messages = 32

[[plugins]]
name = "wasm-register-client"
wasm = "../../target/wasm32-unknown-unknown/debug/cubex_wasm_register_client_plugin.wasm"
args = ["7", "42"]
autostart = true

[[plugins]]
name = "wasm-register-bank"
wasm = "../../target/wasm32-unknown-unknown/debug/cubex_wasm_register_bank_plugin.wasm"

[[plugins]]
name = "wasm-print"
wasm = "../../target/wasm32-unknown-unknown/debug/cubex_wasm_print_plugin.wasm"

[[routes]]
name = "wasm-register-write"
source = "wasm-register-client"
topic = "register.write"
payload = "record"
to = ["wasm-register-bank"]

[[routes]]
name = "wasm-register-read"
source = "wasm-register-client"
topic = "register.read"
payload = "record"
to = ["wasm-register-bank"]

[[routes]]
name = "wasm-write-ack-to-print"
source = "wasm-register-bank"
topic = "register.written"
payload = "record"
to = ["wasm-print"]

[[routes]]
name = "wasm-read-value-to-print"
source = "wasm-register-bank"
topic = "register.value"
payload = "record"
to = ["wasm-print"]
